import { InstagramLink } from "./InstagramLink.jsx";
import { sitePath } from "./paths.js";

const navItems = [["Start", "#start"], ["Rugby", "#rugby"], ["Training", "#training"], ["Vereinsleben", sitePath("aktuelles.html")], ["Komm vorbei", sitePath("kontakt.html")]];

export function App() {
  return (
    <main className="site-shell">
      <header className="site-header">
        <a className="brand" href="#start" aria-label="Wild Hogs Rugby Hohnstorf Startseite"><img src={sitePath("assets/wild-hogs-wappen.png")} alt="Wild Hogs Rugby Wappen" /><span><strong>WILD HOGS</strong><small>Rugby · TuS Hohnstorf/Elbe</small></span></a>
        <nav aria-label="Hauptnavigation">{navItems.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</nav>
        <a className="header-cta" href={sitePath("kontakt.html")}>Zum Probetraining <span>→</span></a>
      </header>

      <section id="start" className="hero section-dark"><div className="hero-image" aria-hidden="true" /><div className="hero-copy"><p className="eyebrow">Mehr als ein Sport · Eine Gemeinschaft</p><h1>RUGBY<br /><em>FÜR ALLE.</em></h1><p className="hero-lede">Die Wild Hogs sind die Jugend-Rugbymannschaft des TuS Hohnstorf/Elbe. Komm vorbei, lern uns kennen und erlebe, wie viel Spaß Rugby im Team macht.</p><a className="button button-red" href={sitePath("kontakt.html")}>Zum Probetraining <span>→</span></a></div><div className="hero-caption">Kleine Stadt.<br /><strong>Starkes Team.</strong></div></section>
      <section className="intro-band" aria-label="Wofür die Wild Hogs stehen"><p>Bewegung</p><span>·</span><p>Freundschaft</p><span>·</span><p>Fairness</p><span>·</span><p>Hohnstorf</p></section>

      <section id="rugby" className="story section-light split-section"><div className="story-copy"><p className="eyebrow red-text">Unsere Geschichte</p><h2>RUGBY<br /><em>FÜR MORGEN.</em></h2><p>Was mit einer Idee gegen die Playstation begann, ist in Hohnstorf zu einer echten Rugby-Gemeinschaft gewachsen. Heute gehören 23 Kinder und Jugendliche zum Team.</p><p>Bei uns zählt nicht, wer am lautesten ist. Auf dem Platz wird jeder gebraucht – die Großen und Kräftigen genauso wie die Quirligen und Schnellen.</p><a className="text-link" href="#kontakt">Mehr über die Wild Hogs <span>→</span></a></div><figure className="photo-frame"><img src={sitePath("assets/wild-hogs-real-team.jpg")} alt="Das echte Wild-Hogs-Team auf dem Rugbyplatz" /><figcaption>Ein Team. Ein Dorf. Viele Möglichkeiten.</figcaption></figure></section>

      <section id="training" className="training section-paper"><div><p className="eyebrow red-text">Komm ins Team</p><h2>TRAINING &<br /><em>ALTERSGRUPPEN</em></h2><p>Sportsachen, Trinkflasche und Lust auf Bewegung reichen für den Anfang. Komm einfach vorbei oder melde dich vorher.</p></div><div className="schedule-list"><div className="schedule-row"><strong>Montag</strong><span>16:00 – 18:00 Uhr</span><small>Sportplatz der Schule am Schiffs<wbr />hebewerk</small></div><div className="schedule-row"><strong>Samstag</strong><span>10:00 – 12:00 Uhr</span><small>Sportplatz der Schule am Schiffs<wbr />hebewerk</small></div><div className="schedule-row"><strong>Für wen?</strong><span>Mädchen & Jungen</span><small>Ab 8 Jahre</small></div><div className="schedule-row"><strong>Erwachsene</strong><span>Im Aufbau</span><small>Montag ab 18:00 Uhr · Training nach Absprache · bitte vorher melden</small></div></div><div className="training-location"><div className="training-location-copy"><p className="eyebrow red-text">Hier findet ihr uns</p><h3>Schule am Schiffs<wbr />hebewerk</h3><p>Duvenbornsweg 5a<br />21379 Scharnebeck</p><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Schule+am+Schiffshebewerk%2C+Duvenbornsweg+5a%2C+21379+Scharnebeck" target="_blank" rel="noreferrer">Route in Google Maps <span>↗</span></a></div><figure className="training-location-guide"><img src={sitePath("assets/location/schule-am-schiffshebewerk-wegweiser.png")} alt="Satellitenkarte mit zwei Fußwegen vom Parkplatz zum Sportplatz der Schule am Schiffshebewerk" /><figcaption>Parken am Rundkurs · zwei Fußwege zum Sportplatz</figcaption></figure></div></section>

      <section className="news-teaser section-light"><div><p className="eyebrow red-text">Neben dem Rugbyplatz</p><h2>VEREINSLEBEN<br /><em>& AKTUELLES.</em></h2><p>Besondere Trainingstage, Dorfaktionen und Geschichten aus dem Team bekommen ihren eigenen Platz.</p><div className="news-teaser-actions"><a className="button button-red" href={sitePath("aktuelles.html")}>Zum Vereinsleben <span>→</span></a><InstagramLink className="instagram-cta">Aktuelles auf Instagram</InstagramLink></div></div><div className="news-teaser-media"><img src={sitePath("assets/wild-hogs-strohballen-team.jpeg")} alt="Wild Hogs bei einer Vereinsaktion mit Strohballen" /></div></section>

      <section className="action-photo"><img src={sitePath("assets/wild-hogs-real-team.jpg")} alt="Das Wild-Hogs-Team gemeinsam auf dem Rugbyplatz" /><div className="action-overlay"><p className="eyebrow">Mehr als ein Spiel</p><h2>STARK WERDEN.<br /><em>ZUSAMMEN.</em></h2><a className="button button-red" href={sitePath("kontakt.html")}>Komm vorbei <span>→</span></a></div></section>

      <section id="kontakt" className="contact section-dark contact-teaser"><div className="contact-copy"><p className="eyebrow">Noch Fragen?</p><h2>KOMM<br /><em>VORBEI.</em></h2><p>Manuela Oestreich freut sich auf deine Nachricht. Oder du kommst einfach zum Training – die Wild Hogs heißen dich willkommen.</p><p className="contact-detail">Manuela Oestreich<br /><a href="tel:+4917657949578">0176 57949578</a></p></div><div className="contact-teaser-action"><p>Probetraining, Fragen oder einfach mal kennenlernen?</p><a className="button button-red" href={sitePath("kontakt.html")}>Zum Kontaktformular <span>→</span></a></div></section>

      <footer className="site-footer"><div className="footer-brand"><img src={sitePath("assets/wild-hogs-wappen.png")} alt="" /><span><strong>Wild Hogs Rugby</strong><small>TuS Hohnstorf/Elbe</small></span></div><div className="footer-links"><a href="https://tus-hohnstorf.de/rugby/" target="_blank" rel="noreferrer">TuS Hohnstorf/Elbe</a><InstagramLink /><a href={sitePath("kontakt.html")}>Kontakt</a></div><p>Starke Kids. Echter Teamgeist.</p></footer>
    </main>
  );
}
