import { InstagramLink } from "./InstagramLink.jsx";
import { english, localizedPath } from "./locale.jsx";
import { sitePath } from "./paths.js";
import { SiteFooter, SiteHeader } from "./SiteChrome.jsx";

export function App() {
  return <main className="site-shell">
    <SiteHeader />
    <section id="start" className="hero section-dark">
      <div className="hero-image" aria-hidden="true" />
      <div className="hero-copy"><p className="eyebrow">{english ? "More than a sport · A community" : "Mehr als ein Sport · Eine Gemeinschaft"}</p><h1>RUGBY<br /><em>{english ? "FOR EVERYONE." : "FÜR ALLE."}</em></h1><p className="hero-lede">{english ? "The Wild Hogs are the youth rugby team of TuS Hohnstorf/Elbe. Come along, meet us and discover how much fun rugby can be together." : "Die Wild Hogs sind die Jugend-Rugbymannschaft des TuS Hohnstorf/Elbe. Komm vorbei, lern uns kennen und erlebe, wie viel Spaß Rugby im Team macht."}</p><a className="button button-red" href={localizedPath("kontakt.html")}>{english ? "Try rugby" : "Zum Probetraining"} <span>→</span></a></div>
      <div className="hero-caption">{english ? "Small village." : "Kleines Dorf."}<br /><strong>{english ? "Strong team." : "Starkes Team."}</strong></div>
    </section>
    <section className="intro-band" aria-label={english ? "What the Wild Hogs stand for" : "Wofür die Wild Hogs stehen"}><p>{english ? "Movement" : "Bewegung"}</p><span>·</span><p>{english ? "Friendship" : "Freundschaft"}</p><span>·</span><p>{english ? "Fair play" : "Fairness"}</p><span>·</span><p>Hohnstorf</p></section>
    <section id="rugby" className="story section-light split-section"><div className="story-copy"><p className="eyebrow red-text">{english ? "Our story" : "Unsere Geschichte"}</p><h2>RUGBY<br /><em>{english ? "FOR THE FUTURE." : "FÜR MORGEN."}</em></h2><p>{english ? "What began as an idea to get kids away from the PlayStation has grown into a real rugby community in Hohnstorf. Today, 23 children and teenagers are part of the team." : "Was mit einer Idee gegen die Playstation begann, ist in Hohnstorf zu einer echten Rugby-Gemeinschaft gewachsen. Heute gehören 23 Kinder und Jugendliche zum Team."}</p><p>{english ? "It doesn't matter who's the loudest. Everyone has a part to play on the pitch – the big and strong, and the quick and nimble alike." : "Bei uns zählt nicht, wer am lautesten ist. Auf dem Platz wird jeder gebraucht – die Großen und Kräftigen genauso wie die Quirligen und Schnellen."}</p><a className="text-link" href="#kontakt">{english ? "Come and meet us" : "Lerne uns kennen"} <span>→</span></a></div><figure className="photo-frame intro-video-frame"><video controls playsInline preload="metadata" poster={sitePath("assets/wild-hogs-intro-poster-logo.png")} aria-label={english ? "Wild Hogs introduction video" : "Wild-Hogs-Intro-Video"}><source src={sitePath("assets/wild-hogs-intro.m4v")} type="video/mp4" />{english ? "Your browser cannot play this video." : "Dein Browser kann dieses Video nicht abspielen."}</video><figcaption>{english ? "Meet the Wild Hogs." : "Lerne die Wild Hogs kennen."}</figcaption></figure></section>
    <section id="training" className="training section-paper"><div><p className="eyebrow red-text">{english ? "Join the team" : "Komm ins Team"}</p><h2>TRAINING &<br /><em>{english ? "AGE GROUPS" : "ALTERSGRUPPEN"}</em></h2><p>{english ? "Sports clothes, a water bottle and a willingness to get moving are all you need. Just come along or get in touch beforehand." : "Sportsachen, Trinkflasche und Lust auf Bewegung reichen für den Anfang. Komm einfach vorbei oder melde dich vorher."}</p></div><div className="schedule-list"><div className="schedule-row"><strong>{english ? "Monday" : "Montag"}</strong><span>{english ? "16:00 – 18:00" : "16:00 – 18:00 Uhr"}</span><small>{english ? "Sports field at Schule am Schiffshebewerk" : <>Sportplatz der Schule am Schiffs<wbr />hebewerk</>}</small></div><div className="schedule-row"><strong>{english ? "Saturday" : "Samstag"}</strong><span>{english ? "10:00 – 12:00" : "10:00 – 12:00 Uhr"}</span><small>{english ? "Sports field at Schule am Schiffshebewerk" : <>Sportplatz der Schule am Schiffs<wbr />hebewerk</>}</small></div><div className="schedule-row"><strong>{english ? "Who?" : "Für wen?"}</strong><span>{english ? "Girls & boys" : "Mädchen & Jungen"}</span><small>{english ? "From age 8" : "Ab 8 Jahre"}</small></div><div className="schedule-row"><strong>{english ? "Adults" : "Erwachsene"}</strong><span>{english ? "Group in development" : "Im Aufbau"}</span><small>{english ? "Mondays from 18:00 · Training by arrangement · please contact us first" : "Montag ab 18:00 Uhr · Training nach Absprache · bitte vorher melden"}</small></div></div><div className="training-location"><div className="training-location-copy"><p className="eyebrow red-text">{english ? "Find us here" : "Hier findet ihr uns"}</p><h3>Schule am Schiffs<wbr />hebewerk</h3><p>Duvenbornsweg 5a<br />21379 Scharnebeck</p><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Schule+am+Schiffshebewerk%2C+Duvenbornsweg+5a%2C+21379+Scharnebeck" target="_blank" rel="noopener noreferrer">{english ? "Directions in Google Maps" : "Route in Google Maps"} <span>↗</span></a></div><figure className="training-location-guide"><img src={sitePath("assets/location/schule-am-schiffshebewerk-wegweiser.png")} alt={english ? "Aerial map showing two walking routes from the car park to the sports field" : "Satellitenkarte mit zwei Fußwegen vom Parkplatz zum Sportplatz der Schule am Schiffshebewerk"} /><figcaption>{english ? "Parking by the loop · two walking routes to the pitch" : "Parken am Rundkurs · zwei Fußwege zum Sportplatz"}</figcaption></figure></div></section>
    <section className="news-teaser section-light"><div><p className="eyebrow red-text">{english ? "Beyond the rugby pitch" : "Neben dem Rugbyplatz"}</p><h2>{english ? "CLUB LIFE" : "VEREINSLEBEN"}<br /><em>{english ? "& NEWS." : "& AKTUELLES."}</em></h2><p>{english ? "Special training days, village events and stories from the team have a place of their own." : "Besondere Trainingstage, Dorfaktionen und Geschichten aus dem Team bekommen ihren eigenen Platz."}</p><div className="news-teaser-actions"><a className="button button-red" href={localizedPath("aktuelles.html")}>{english ? "Explore club life" : "Zum Vereinsleben"} <span>→</span></a><InstagramLink className="instagram-cta">{english ? "Latest on Instagram" : "Aktuelles auf Instagram"}</InstagramLink></div></div><div className="news-teaser-media"><img src={sitePath("assets/wild-hogs-strohballen-team.jpeg")} alt={english ? "Wild Hogs at a straw-bale club event" : "Wild Hogs bei einer Vereinsaktion mit Strohballen"} /></div></section>
    <section className="action-photo"><img src={sitePath("assets/wild-hogs-real-team.jpg")} alt={english ? "The Wild Hogs together on the rugby pitch" : "Das Wild-Hogs-Team gemeinsam auf dem Rugbyplatz"} /><div className="action-overlay"><p className="eyebrow">{english ? "More than a game" : "Mehr als ein Spiel"}</p><h2>{english ? "GROW STRONG." : "STARK WERDEN."}<br /><em>{english ? "TOGETHER." : "ZUSAMMEN."}</em></h2><a className="button button-red" href={localizedPath("kontakt.html")}>{english ? "Join us" : "Komm vorbei"} <span>→</span></a></div></section>
    <section id="kontakt" className="contact section-dark contact-teaser"><div className="contact-copy"><p className="eyebrow">{english ? "Questions?" : "Noch Fragen?"}</p><h2>{english ? "COME" : "KOMM"}<br /><em>{english ? "ALONG." : "VORBEI."}</em></h2><p>{english ? "Manuela Oestreich would love to hear from you. Or just come to training – the Wild Hogs will welcome you." : "Manuela Oestreich freut sich auf deine Nachricht. Oder du kommst einfach zum Training – die Wild Hogs heißen dich willkommen."}</p><p className="contact-detail">Manuela Oestreich<br /><a href="tel:+4917657949578">0176 57949578</a><br /><a href="mailto:manu@wildhogsrugby.de">manu@wildhogsrugby.de</a></p><p className="contact-general">{english ? "General enquiries" : "Allgemeine Anfragen"}<br /><a href="mailto:info@wildhogsrugby.de">info@wildhogsrugby.de</a></p></div><div className="contact-teaser-action"><p>{english ? "Try rugby, ask a question or simply get to know us." : "Probetraining, Fragen oder einfach mal kennenlernen?"}</p><a className="button button-red" href={localizedPath("kontakt.html")}>{english ? "Contact us" : "Zum Kontakt"} <span>→</span></a></div></section>
    <SiteFooter />
  </main>;
}
