import { useState } from "react";
import { InstagramLink } from "./InstagramLink.jsx";
import { sitePath } from "./paths.js";

function ContactHeader() {
  return <header className="site-header"><a className="brand" href={`${sitePath()}#start`} aria-label="Zur Wild Hogs Startseite"><img src={sitePath("assets/wild-hogs-wappen.png")} alt="Wild Hogs Rugby Wappen" /><span><strong>WILD HOGS</strong><small>Kontakt · TuS Hohnstorf/Elbe</small></span></a><nav aria-label="Hauptnavigation"><a href={`${sitePath()}#start`}>Start</a><a href={`${sitePath()}#rugby`}>Rugby</a><a href={`${sitePath()}#training`}>Training</a><a href={sitePath("aktuelles.html")}>Vereinsleben</a><a className="nav-active" href={sitePath("kontakt.html")}>Komm vorbei</a></nav><a className="header-cta" href={sitePath("kontakt.html")}>Zum Probetraining <span>→</span></a></header>;
}

export function Contact() {
  const [sent, setSent] = useState(false);
  return <main className="contact-page site-shell"><ContactHeader /><section className="contact-page-hero section-dark"><div><p className="eyebrow red-text">Komm ins Team</p><h1>PROBETRAINING<br /><em>& KONTAKT.</em></h1><p>Du möchtest Rugby ausprobieren, hast eine Frage oder möchtest einfach mal vorbeischauen? Schreib Manuela oder ruf direkt an.</p></div><div className="contact-page-phone"><span>Ansprechpartnerin</span><strong>Manuela Oestreich</strong><a href="tel:+4917657949578">0176 57949578</a></div></section><section className="contact-page-form section-paper"><div><p className="eyebrow red-text">Schreib uns</p><h2>WIR FREUEN<br /><em>UNS.</em></h2><p>Eine kurze Nachricht reicht. Wir melden uns bei dir und sagen dir, wann du am besten zum Training dazukommen kannst.</p></div><form className="contact-form" onSubmit={(event) => { event.preventDefault(); setSent(true); }}>{sent ? <div className="form-success"><strong>Danke, Nachricht angekommen.</strong><span>Wir melden uns bei dir.</span></div> : <><label>Name<input required name="name" placeholder="Dein Name" /></label><label>E-Mail<input required type="email" name="email" placeholder="deine@email.de" /></label><label>Nachricht<textarea required name="message" placeholder="Ich möchte Rugby ausprobieren …" rows="5" /></label><button className="button button-red" type="submit">Nachricht senden <span>→</span></button></>}</form></section><footer className="site-footer"><div className="footer-brand"><img src={sitePath("assets/wild-hogs-wappen.png")} alt="" /><span><strong>Wild Hogs Rugby</strong><small>TuS Hohnstorf/Elbe</small></span></div><div className="footer-links"><a href={sitePath()}>Zur Rugby-Seite</a><a href={sitePath("aktuelles.html")}>Vereinsleben</a><InstagramLink /><a href="tel:+4917657949578">Manu anrufen</a></div><p>Starke Kids. Echter Teamgeist.</p></footer></main>;
}
