import { english } from "./locale.jsx";
import { SiteFooter, SiteHeader } from "./SiteChrome.jsx";

export function Privacy() {
  return <main className="privacy-page site-shell">
    <SiteHeader />
    <section className="privacy-hero section-dark"><p className="eyebrow red-text">Wild Hogs Rugby</p><h1>{english ? "PRIVACY." : "DATENSCHUTZ."}</h1><p>{english ? "How this website handles personal data. Current as of 28 September 2026." : "So geht diese Website mit personenbezogenen Daten um. Stand: 28.09.2026."}</p></section>
    <div className="privacy-content section-light">
      <section><h2>{english ? "Who is responsible?" : "Wer ist verantwortlich?"}</h2><p>Christopher Harms<br />Am Osterberg 7<br />21379 Echem<br />{english ? "Germany" : "Deutschland"}<br /><a href="mailto:info@wildhogsrugby.de">info@wildhogsrugby.de</a></p></section>
      <section><h2>{english ? "Hosting and access data" : "Hosting und Zugriffsdaten"}</h2><p>{english ? "This website is hosted on GitHub Pages, a service of GitHub, Inc. When you visit a GitHub Pages site, GitHub logs and stores your IP address for security purposes. The technical delivery of the site also involves processing connection data such as the requested page and time of access. We use this hosting to provide the website securely and reliably (Article 6(1)(f) GDPR). For details of GitHub's processing and retention, see GitHub's privacy statement." : "Diese Website wird über GitHub Pages, einen Dienst von GitHub, Inc., bereitgestellt. Laut GitHub wird beim Besuch einer GitHub-Pages-Seite die IP-Adresse zu Sicherheitszwecken protokolliert und gespeichert. Bei der technischen Auslieferung fallen außerdem Verbindungsdaten wie die aufgerufene Seite und der Zeitpunkt des Abrufs an. Wir nutzen das Hosting, um die Website sicher und zuverlässig bereitzustellen (Art. 6 Abs. 1 lit. f DSGVO). Einzelheiten zur Verarbeitung und Speicherdauer durch GitHub stehen in der Datenschutzerklärung von GitHub."} <a href="https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages#data-collection" target="_blank" rel="noopener noreferrer">GitHub Pages</a> · <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" target="_blank" rel="noopener noreferrer">GitHub Privacy Statement</a></p></section>
      <section><h2>{english ? "Cookies, fonts and videos" : "Cookies, Schriften und Videos"}</h2><p>{english ? "This website itself does not set cookies and does not use an analytics or advertising service. The language switch uses a URL parameter and does not save a preference in your browser. Fonts, photos and videos are served from this website; playing a video does not require an embedded third-party player." : "Diese Website setzt selbst keine Cookies und verwendet keinen Analyse- oder Werbedienst. Die Sprachauswahl erfolgt über einen URL-Parameter; eine Präferenz wird nicht im Browser gespeichert. Schriften, Fotos und Videos werden über diese Website ausgeliefert; zum Abspielen der Videos wird kein eingebetteter Drittanbieter-Player benötigt."}</p></section>
      <section><h2>{english ? "Contact" : "Kontaktaufnahme"}</h2><p>{english ? "You can contact us by phone or email. The contact form currently only prepares a draft in your own email app; it does not send the information from this website to a form service. Your message is transmitted only if you send that email yourself. We process the information you provide to respond to your enquiry (Article 6(1)(b) GDPR for pre-contractual enquiries, otherwise Article 6(1)(f) GDPR). We keep correspondence only as long as needed for the enquiry or applicable legal retention obligations. Web3Forms is not currently integrated; this notice will be updated before an online form service is activated." : "Du kannst uns telefonisch oder per E-Mail kontaktieren. Das Kontaktformular bereitet derzeit lediglich einen Entwurf in deinem eigenen E-Mail-Programm vor; es übermittelt keine Angaben von dieser Website an einen Formulardienst. Erst wenn du die E-Mail selbst absendest, wird deine Nachricht übertragen. Wir verarbeiten deine Angaben zur Beantwortung der Anfrage (bei vorvertraglichen Anfragen Art. 6 Abs. 1 lit. b DSGVO, sonst Art. 6 Abs. 1 lit. f DSGVO). Korrespondenz bewahren wir nur so lange auf, wie es für die Anfrage oder gesetzliche Aufbewahrungspflichten nötig ist. Web3Forms ist derzeit nicht eingebunden; vor Aktivierung eines Online-Formulardienstes wird dieser Hinweis aktualisiert."}</p></section>
      <section><h2>{english ? "Photos and external links" : "Fotos und externe Links"}</h2><p>{english ? "We show photos and videos of club activities on this website. If you have a question about a particular image, please contact us. Links to Instagram, Google Maps and TuS Hohnstorf/Elbe open external websites only when you click them; those providers then process data under their own privacy policies." : "Auf dieser Website zeigen wir Fotos und Videos aus dem Vereinsleben. Bei Fragen zu einem bestimmten Bild melde dich bitte bei uns. Links zu Instagram, Google Maps und TuS Hohnstorf/Elbe öffnen externe Websites erst, wenn du sie anklickst; dort gelten die Datenschutzinformationen der jeweiligen Anbieter."}</p></section>
      <section><h2>{english ? "Your rights" : "Deine Rechte"}</h2><p>{english ? "Subject to the legal requirements, you have the right to access, rectification, erasure, restriction of processing, data portability and objection. You can contact us using the address above. You also have the right to lodge a complaint with a data protection supervisory authority." : "Nach den gesetzlichen Voraussetzungen hast du Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch. Du kannst dich dazu an die oben genannte Adresse wenden. Außerdem kannst du dich bei einer Datenschutzaufsichtsbehörde beschweren."}</p></section>
    </div>
    <SiteFooter />
  </main>;
}
